name: linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Starting Node.js ${{matrix.node-version}} environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Install modules
        run: npm install

      - name: Build project for production
        run: npm run build:prod

      - name: Linting typescript
        run: npm run lint:ts

      - name: Linting css
        run: npm run lint:scss

      - name: Unit testing
        run: npm run test:unit
